org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.176

loader_version_range=[1,)

mod_id=fragmento
mod_name=Fragmento
mod_license=All Rights Reserved
mod_version=0.3-alpha

mod_group_id=com.pgalaxyp.fragmento
mod_authors=pgalaxyp
mod_description=Só o Galaxy fazendo merda